# .github/workflows/ci.yml
name: build & test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4         # installs .NET 8.0.x
        with:
          dotnet-version: '8.0.x'
          cache: true                         # caches global NuGet packages

      # 1️⃣  Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # 2️⃣  Build without restoring again
      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      # 3️⃣  Run tests + coverage without rebuilding
      - name: Run tests with coverage
        run: dotnet test --configuration Release --no-build \
              --collect:"XPlat Code Coverage" \
              --results-directory ./TestResults

      # 4️⃣  (optional) Generate a local HTML report
      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:coverage

      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/*
